.. change::
   :tags: bug, engine
   :tickets: 4429

   Fixed a regression introduced in version 1.2 where a refactor
   of the :class:`.SQLAlchemyError` base exception class introduced an
   inappropriate coercion of a plain string message into Unicode under
   python 2k, which is not handled by the Python interpreter for characters
   outside of the platform's encoding (typically ascii).  The
   :class:`.SQLAlchemyError` class now passes a bytestring through under
   Py2K for ``__str__()`` as is the behavior of exception objects in general
   under Py2K, does a safe coercion to unicode utf-8 with
   backslash fallback for ``__unicode__()``.  For Py3K the message is
   typically unicode already, but if not is again safe-coerced with utf-8
   with backslash fallback for the ``__str__()`` method.